name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:

  testing:
    name: Test
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Tools
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build test.project.json -o test.rbxlx

      - name: Run
        run: run-in-roblox --place test.rbxlx --script tests/.server.lua


  linting:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Install Selene
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Check
        run: selene src/*.lua