name: Discord release

on:
  release:
    types: [published]

jobs:
  post:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Get release name
      id: get-release-name
      run: "echo ::set-output name=name::${RELEASE:-$TAG}"
      env:
        RELEASE: ${{ github.event.release.name }}
        TAG: ${{ github.event.release.tag_name }}

    - name: Post release
      uses: kludge-cs/gitcord-release-changelogger@v3.0.0
      with:
        release-body: ${{ github.event.release.body }}
        release-name: ${{ steps.get-release-name.outputs.name }}
        webhook-url: ${{ secrets.RELEASE_WEBHOOK }}